# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build with maven
        run: mvn clean install -DskipTests

        # Run all unit tests
      - name: Run tests with maven
        run: mvn test

      #Publish unit tests reports
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.6
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: target/surefire-reports/**/*.xml

      # Runs a single command using the runners shell
      - name: Run pitest with maven
        run: mvn org.pitest:pitest-maven:mutationCoverage

      #Publish mutation tests reports
      - name: Publish mutation testing results as artifact
        uses: actions/upload-artifact@v2
        with:
          name: mutation_testing_results
          path: src/docs/pit-reports/

      #Compute documentation
      - name: Publish documentation with asciidoctor
        run:  mvn asciidoctor:process-asciidoc

      #Publish documentation
      - name: Publish to github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/generated-docs/
          enable_jekyll: true
